import re

from pipeline.kb.render import render_summary
from pipeline.models import Citation, Contradiction, Unit, UnitVersion

AUTHOR_META = {"author_id": "A-jane-doe", "canonical_name": "Jane Doe", "aliases": ["J. Doe", "Dr Doe"], "type": "person"}

TAXONOMY = {
    "T-rest": {"name": "Rest Body", "path": "Body > Immortal Yogi > Rest Body", "level": "stage", "domain": "Body"},
    "T-think": {"name": "Think", "path": "Mind > Prodigy Autodidact > Think", "level": "stage", "domain": "Mind"},
}

RESOURCES = [
    {"resource_id": "R-old", "title": "Old talk", "published_date": "2010", "date_precision": "year", "stage_id": "T-rest", "stage_path": "", "source_type": "youtube", "source_url": "https://youtu.be/old", "raw_file_url": ""},
    {"resource_id": "R-new", "title": "New book | vol 2", "published_date": "2024-02-10", "date_precision": "day", "stage_id": "T-think", "stage_path": "", "source_type": "pdf", "source_url": "", "raw_file_url": "https://drive/new"},
    {"resource_id": "R-und", "title": "Undated post", "published_date": "", "date_precision": "unknown", "stage_id": "", "stage_path": "", "source_type": "web", "source_url": "https://blog/x", "raw_file_url": ""},
]

KB_CFG = {"max_doc_chars": 900000, "obsolescence_years": 7}


def unit(id_, name, type_, stages, cites, **kw):
    data = dict(
        id=id_, author_id="A-jane-doe", type=type_, name=name, stages=stages,
        description=f"{name} description.", details=f"{name} details.",
        citations=[Citation(resource_id=r, location=loc, quote="q", verified=True, score=100) for r, loc in cites],
    )
    data.update(kw)
    return Unit(**data)


UNITS = [
    unit("U-1", "Sleep first", "principle", ["T-rest"], [("R-new", "p. 3"), ("R-old", "12:00")], aliases=["Rest first"], notes="Key idea."),
    unit("U-2", "Wind-down", "procedure", ["T-rest", "T-think"], [("R-new", "p. 4")],
         versions=[UnitVersion(date="2010", resource_id="R-old", summary="old form"), UnitVersion(date="2024-02-10", resource_id="R-new", what_changed="added a cold room step")]),
    unit("U-3", "Ancient rule", "claim", ["T-think"], [("R-old", "05:00")]),
    unit("U-4", "Circadian rhythm", "glossary", ["T-think"], [("R-new", "p. 9")], description="The body's 24 hour cycle."),
    unit("U-5", "Contested claim", "claim", ["T-think"], [("R-new", "p. 10")], status="contradicted",
         contradictions=[Contradiction(resource_id="R-new", claim="Later says the opposite", conflicts_with="Contested claim description.")]),
    unit("U-6", "Homeless card", "technique", [], [("R-und", "")]),
    unit("U-7", "Old superseded", "technique", ["T-rest"], [("R-new", "p. 1")], status="superseded"),
]

CHANGELOG = [{"version": 1, "date": "2025-01-01", "note": "first run"}, {"version": 2, "date": "2026-09-19", "note": "added R-new"}]


def test_summary_sections_and_cards():
    out = render_summary(AUTHOR_META, UNITS, RESOURCES, TAXONOMY, KB_CFG, 2, CHANGELOG, "2026-09-19T10:00:00Z")
    assert list(out) == ["summary.md"]
    text = out["summary.md"]
    assert text.startswith("Generated by the AI Primer summary agent, version 2, 2026-09-19. Do not edit by hand")
    for heading in [
        "# Summary: Jane Doe", "## Author profile", "## Sources", "## Reading guide", "## Cards: Body", "## Cards: Mind",
        "## Cards: Unassigned", "## Evolution timeline", "## Contradictions and open questions", "## Obsolescence watch",
        "## Glossary", "## Changelog",
    ]:
        assert heading in text, heading
    # profile
    assert "- Canonical name: Jane Doe" in text and "J. Doe, Dr Doe" in text
    assert "- Sources: 3" in text and "- Cards: 7" in text and "2010 -> 2024-02-10" in text
    # sources table sorted by date, unknown last, pipes escaped
    rows = [l for l in text.splitlines() if l.startswith("| ") and "| --- " not in l and "Date" not in l and "Version" not in l]
    assert rows[0].startswith("| 2010 | Old talk | youtube | https://youtu.be/old")
    assert rows[1].startswith("| 2024-02-10 | New book / vol 2 | pdf | https://drive/new")
    assert rows[2].startswith("| unknown | Undated post | web | https://blog/x")
    # cards grouped Domain > Stage > type, with names as h4
    body_pos = text.index("## Cards: Body")
    mind_pos = text.index("## Cards: Mind")
    assert body_pos < mind_pos
    assert "### Body > Immortal Yogi > Rest Body" in text and "### Mind > Prodigy Autodidact > Think" in text
    card = text[text.index("#### Sleep first") : text.index("#### Wind-down")]
    assert "Also known as: Rest first" in card
    assert "Sleep first description." in card and "Sleep first details." in card and "Notes: Key idea." in card
    assert "- R-new (p. 3)" in card and "- R-old (12:00)" in card
    # principles come before procedures inside a stage
    assert text.index("**Principles**") < text.index("**Procedures**")
    # unit with two stages appears once, under the first, with an "Also in" line
    assert text.count("#### Wind-down") == 1
    assert "Also in: Mind > Prodigy Autodidact > Think" in text
    assert "#### Homeless card" in text[text.index("## Cards: Unassigned") :]
    # glossary
    glossary = text[text.index("## Glossary") : text.index("## Changelog")]
    assert "- Circadian rhythm: The body's 24 hour cycle." in glossary
    # changelog rows
    assert "| 2 | 2026-09-19 | added R-new |" in text
    # no triple blank lines
    assert "\n\n\n" not in text


def test_evolution_contradictions_and_obsolescence():
    out = render_summary(AUTHOR_META, UNITS, RESOURCES, TAXONOMY, KB_CFG, 1, CHANGELOG, "2026-09-19")
    text = out["summary.md"]
    evo = text[text.index("## Evolution timeline") : text.index("## Contradictions")]
    assert "Wind-down (U-2)" in evo
    assert evo.index("2010 - Old talk") < evo.index("2024-02-10 - New book")
    assert "added a cold room step" in evo
    assert "Sleep first" not in evo
    contra = text[text.index("## Contradictions") : text.index("## Obsolescence")]
    assert "Contested claim (U-5)" in contra and "Later says the opposite" in contra
    obs = text[text.index("## Obsolescence watch") : text.index("## Glossary")]
    assert "Ancient rule (U-3)" in obs and "2010" in obs
    assert "Old superseded (U-7)" in obs and "superseded" in obs
    assert "Sleep first" not in obs  # its newest source is 2024
    assert "Homeless card" not in obs  # undated source: not flagged


def test_split_into_parts_above_max_doc_chars():
    out = render_summary(AUTHOR_META, UNITS, RESOURCES, TAXONOMY, {**KB_CFG, "max_doc_chars": 500}, 3, CHANGELOG, "2026-09-19")
    assert set(out) == {"summary.md", "summary - Body.md", "summary - Mind.md", "summary - Unassigned.md"}
    hub = out["summary.md"]
    assert "## Parts" in hub and "summary - Body" in hub and "summary - Mind" in hub
    assert "#### " not in hub  # no cards in the hub
    assert "## Evolution timeline" in hub and "## Glossary" in hub and "## Changelog" in hub
    body = out["summary - Body.md"]
    assert body.startswith("Generated by the AI Primer summary agent, version 3")
    assert "# Summary: Jane Doe - Body" in body
    assert "#### Sleep first" in body and "#### Ancient rule" not in body
    assert "## Cards: Body" in body and "## Evolution timeline" not in body
    mind = out["summary - Mind.md"]
    assert "#### Ancient rule" in mind and "#### Circadian rhythm" in mind


def test_empty_store_renders():
    out = render_summary({"canonical_name": "Nobody"}, [], [], {}, {}, 1, [], "2026-01-01T00:00:00Z")
    text = out["summary.md"]
    assert "# Summary: Nobody" in text
    assert "No card has more than one dated version yet." in text
    assert "None recorded." in text
    assert "No glossary terms yet." in text
    assert re.search(r"- Date span: unknown", text)
