from __future__ import annotations

from pipeline.apify_yt import ApifyYouTube, metadata_guess_from_video, parse_duration, parse_transcript_item, parse_video_item


def test_parse_duration():
    assert parse_duration(754) == 754
    assert parse_duration("12:34") == 754
    assert parse_duration("1:02:03") == 3723
    assert parse_duration("PT1H2M3S") == 3723
    assert parse_duration("") is None and parse_duration("x") is None


def test_parse_video_item_shapes():
    a = parse_video_item({"id": "abcdefghijk", "title": "T", "channelName": "Chan", "channelUrl": "https://youtube.com/@chan", "date": "2021-06-10T00:00:00Z", "duration": "10:00"})
    assert a["video_id"] == "abcdefghijk" and a["published_date"] == "2021-06-10" and a["duration_sec"] == 600 and a["url"].endswith("abcdefghijk")
    b = parse_video_item({"url": "https://www.youtube.com/watch?v=zzzzzzzzzzz", "title": "U", "channel": {"name": "C2", "url": "https://x"}, "publishedAt": "2 years ago", "type": "short"})
    assert b["video_id"] == "zzzzzzzzzzz" and b["channel_name"] == "C2" and b["date_precision"] == "year" and b["is_short"]
    g = metadata_guess_from_video(a)
    assert g.title == "T" and g.author_raw == "Chan" and g.published_date == "2021-06-10" and g.confidence >= 0.9


def test_parse_transcript_item_shapes():
    t = parse_transcript_item({"videoId": "abcdefghijk", "transcript": [{"start": 0, "dur": 2, "text": "hi"}], "language": "en", "isAutoGenerated": False})
    assert t["video_id"] == "abcdefghijk" and t["kind"] == "manual" and isinstance(t["segments"], list)
    t2 = parse_transcript_item({"url": "https://youtu.be/abcdefghijk", "transcript": "plain text here"})
    assert t2["video_id"] == "abcdefghijk" and t2["segments"] is None and t2["text"] == "plain text here"


def test_client_caching_and_batches(settings, fake_apify, tmp_path):
    fake_apify.responses["apidojo/youtube-scraper"] = lambda inp: [{"id": u.rsplit("=", 1)[-1] if "watch?v=" in u else f"vid{i:08d}", "title": f"T{i}", "channelName": "Chan", "date": "2020-01-0%d" % (i % 9 + 1)} for i, u in enumerate(inp["startUrls"])]
    fake_apify.responses["supreme_coder/youtube-transcript-scraper"] = lambda inp: [{"videoId": u.rsplit("=", 1)[-1], "transcript": [{"start": 0, "dur": 1, "text": "hello"}]} for u in inp["startUrls"]]
    yt = ApifyYouTube(fake_apify, settings, cache_dir=tmp_path / "yt")
    meta = yt.video_metadata(["abcdefghijk"])
    assert meta["abcdefghijk"]["title"] == "T0"
    yt.video_metadata(["abcdefghijk"])  # cached: no extra call
    assert len(fake_apify.calls) == 1
    ids = [f"id{i:09d}" for i in range(60)]
    tr = yt.transcripts(ids)
    assert len(tr) == 60
    transcript_calls = [c for c in fake_apify.calls if c[0] == "supreme_coder/youtube-transcript-scraper"]
    assert len(transcript_calls) == 3  # batches of 25
    assert yt.estimate_cost(100) == round(100 * (0.0005 + 0.0007), 4)
    assert len(yt.run_ids) == 4 and yt.cost_usd > 0


def test_channel_listing_and_schema_fetch(settings, fake_apify, tmp_path, monkeypatch):
    fake_apify.responses["apidojo/youtube-scraper"] = [{"id": f"chan{i:07d}", "title": f"V{i}", "channelName": "Chan", "date": "2021-01-01"} for i in range(5)] + [{"id": "chan0000001", "title": "dup"}]
    yt = ApifyYouTube(fake_apify, settings, cache_dir=tmp_path / "yt")
    videos = yt.channel_videos("https://www.youtube.com/@chan/videos")
    assert len(videos) == 5
    fake_apify.schemas["apidojo/youtube-scraper"] = {"properties": {"startUrls": {"type": "array", "items": {"type": "object"}}, "maxItems": {"type": "integer"}}}
    fake_apify.schemas["supreme_coder/youtube-transcript-scraper"] = {"properties": {"videoUrls": {"type": "array", "items": {"type": "string"}}}}
    import pipeline.apify_yt as mod

    saved = {}
    monkeypatch.setattr(mod, "save_config", lambda s: saved.setdefault("called", True))
    report = yt.fetch_and_store_schemas()
    assert report["metadata"]["fields"] == {"start_urls_key": "startUrls", "start_urls_format": "objects", "max_results_key": "maxItems"}
    assert report["transcript"]["fields"]["start_urls_key"] == "videoUrls"
    assert saved["called"]
    # the new template shapes the next request
    yt.video_metadata(["newvideo001"], use_cache=False)
    actor, inp = fake_apify.calls[-1]
    assert inp["startUrls"] == [{"url": "https://www.youtube.com/watch?v=newvideo001"}] and inp["maxItems"] == 1
