"""Render the author summary (markdown, later converted to a Google Doc) from the unit store."""

from __future__ import annotations

import re
from collections import defaultdict
from datetime import date
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from pipeline.models import UNIT_TYPES, Unit

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"
UNASSIGNED = "Unassigned"
TYPE_LABELS = {
    "principle": "Principles",
    "concept": "Concepts",
    "technique": "Techniques",
    "drill": "Drills",
    "exercise": "Exercises",
    "list": "Lists",
    "script": "Scripts",
    "example": "Examples",
    "glossary": "Glossary terms",
    "procedure": "Procedures",
    "claim": "Claims",
    "mistake": "Mistakes",
    "dataset": "Datasets",
}
_DEFAULTS = {"max_doc_chars": 900_000, "obsolescence_years": 7}


def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


def banner_text(version: int, generated_at: str) -> str:
    return (
        f"Generated by the AI Primer summary agent, version {version}, {(generated_at or '')[:10]}. "
        "Do not edit by hand: changes are overwritten. Give feedback as comments or in chat."
    )


# --------------------------------------------------------------------------- date helpers


def _pad_date(value: str, end_of_period: bool = True) -> str:
    """"YYYY" / "YYYY-MM" -> full ISO date so dates of mixed precision compare sensibly."""
    v = (value or "").strip()
    if re.fullmatch(r"\d{4}", v):
        return f"{v}-12-31" if end_of_period else f"{v}-01-01"
    if re.fullmatch(r"\d{4}-\d{2}", v):
        return f"{v}-28" if end_of_period else f"{v}-01"
    return v[:10]


def _known_date(resource: dict) -> str:
    if (resource.get("date_precision") or "unknown") == "unknown":
        return ""
    return str(resource.get("published_date") or "")


def _cutoff(generated_at: str, years: int) -> str:
    try:
        g = date.fromisoformat((generated_at or "")[:10])
    except ValueError:
        g = date.today()
    try:
        return g.replace(year=g.year - years).isoformat()
    except ValueError:  # 29 February
        return g.replace(year=g.year - years, day=28).isoformat()


# --------------------------------------------------------------------------- context builders


def _sources_rows(resources: list[dict]) -> list[dict]:
    rows = []
    for r in resources:
        d = _known_date(r)
        rows.append(
            {
                "date": d or "unknown",
                "sort": (0, _pad_date(d, end_of_period=False)) if d else (1, ""),
                "title": (r.get("title") or r.get("resource_id") or "").replace("|", "/"),
                "type": r.get("source_type") or "",
                "link": r.get("source_url") or r.get("raw_file_url") or "",
            }
        )
    rows.sort(key=lambda x: x["sort"])
    for row in rows:
        row.pop("sort")
    return rows


def _profile(author_meta: dict, resources: list[dict], units: list[Unit]) -> dict:
    dates = sorted(d for d in (_known_date(r) for r in resources) if d)
    span = f"{dates[0]} -> {dates[-1]}" if dates else "unknown"
    return {
        "canonical_name": author_meta.get("canonical_name") or author_meta.get("author_id") or "",
        "aliases": [a for a in (author_meta.get("aliases") or []) if a],
        "n_sources": len(resources),
        "date_span": span,
        "n_cards": len(units),
    }


def _stage_info(stage_id: str, taxonomy: dict[str, dict]) -> tuple[str, str]:
    node = taxonomy.get(stage_id) if stage_id else None
    if not node:
        return UNASSIGNED, UNASSIGNED
    domain = node.get("domain") or (node.get("path") or "").split(" > ")[0] or UNASSIGNED
    path = node.get("path") or node.get("name") or stage_id
    return domain, path


def _card(u: Unit, taxonomy: dict[str, dict]) -> dict:
    seen: set[tuple[str, str]] = set()
    sources = []
    for c in u.citations:
        key = (c.resource_id, c.location)
        if key in seen:
            continue
        seen.add(key)
        sources.append(f"{c.resource_id} ({c.location})" if c.location else c.resource_id)
    also_in = [_stage_info(s, taxonomy)[1] for s in u.stages[1:]]
    status_line = "" if u.status == "active" else f"Status: {u.status.replace('_', ' ')}"
    return {
        "unit_id": u.id,
        "name": u.name,
        "type": u.type,
        "aliases": list(u.aliases),
        "status_line": status_line,
        "also_in": also_in,
        "description": u.description.strip(),
        "details": u.details.strip(),
        "notes": u.notes.strip(),
        "sources": sources or ["none"],
    }


def _domains(units: list[Unit], taxonomy: dict[str, dict]) -> list[dict]:
    tree: dict[str, dict[str, dict[str, list[Unit]]]] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for u in units:
        domain, path = _stage_info(u.stages[0] if u.stages else "", taxonomy)
        tree[domain][path][u.type].append(u)
    domains = []
    for domain in sorted(tree, key=lambda d: (d == UNASSIGNED, d.lower())):
        stages = []
        for path in sorted(tree[domain], key=lambda p: (p == UNASSIGNED, p.lower())):
            types = []
            for t in UNIT_TYPES:
                group = tree[domain][path].get(t)
                if not group:
                    continue
                types.append(
                    {
                        "type": t,
                        "label": TYPE_LABELS.get(t, t.title()),
                        "units": [_card(u, taxonomy) for u in sorted(group, key=lambda x: x.name.lower())],
                    }
                )
            stages.append({"path": path, "types": types})
        domains.append({"name": domain, "stages": stages, "n_cards": sum(len(t["units"]) for s in stages for t in s["types"])})
    return domains


def _evolution(units: list[Unit], res_by_id: dict[str, dict]) -> list[dict]:
    out = []
    for u in sorted(units, key=lambda x: x.name.lower()):
        if len(u.versions) < 2:
            continue
        versions = []
        for v in sorted(u.versions, key=lambda v: v.date):
            r = res_by_id.get(v.resource_id, {})
            source = r.get("title") or v.resource_id
            if r.get("title"):
                source = f"{source} ({v.resource_id})"
            versions.append(
                {
                    "date": v.date or "undated",
                    "source": source,
                    "what_changed": v.what_changed.strip(),
                    "summary": v.summary.strip(),
                }
            )
        out.append({"unit_id": u.id, "name": u.name, "versions": versions})
    return out


def _contradictions(units: list[Unit], res_by_id: dict[str, dict]) -> list[dict]:
    out = []
    for u in sorted(units, key=lambda x: x.name.lower()):
        items = []
        for c in u.contradictions:
            r = res_by_id.get(c.resource_id, {})
            src = c.resource_id + (f", {_known_date(r)}" if _known_date(r) else "")
            item = f"{src}: {c.claim}"
            if c.conflicts_with:
                item += f" (conflicts with: {c.conflicts_with})"
            items.append(item)
        if u.status == "needs_review":
            items.append("Open question: this card is flagged for review.")
        if items:
            out.append({"unit_id": u.id, "name": u.name, "status": u.status.replace("_", " "), "entries": items})
    return out


def _obsolescence(units: list[Unit], res_by_id: dict[str, dict], generated_at: str, years: int) -> list[dict]:
    cutoff = _cutoff(generated_at, years)
    out = []
    for u in sorted(units, key=lambda x: x.name.lower()):
        if u.status == "superseded":
            out.append({"unit_id": u.id, "name": u.name, "reason": "superseded"})
            continue
        if u.status != "active":
            continue
        dates = [_known_date(res_by_id.get(c.resource_id, {})) for c in u.citations]
        dates = [d for d in dates if d]
        if not dates:
            continue
        newest = max(dates, key=lambda d: _pad_date(d))
        if _pad_date(newest) < cutoff:
            out.append(
                {
                    "unit_id": u.id,
                    "name": u.name,
                    "reason": f"newest source dated {newest}, older than {years} years",
                }
            )
    return out


def _glossary(units: list[Unit]) -> list[dict]:
    return [
        {"name": u.name, "description": u.description.strip().replace("\n", " ")}
        for u in sorted((x for x in units if x.type == "glossary"), key=lambda x: x.name.lower())
    ]


def _tidy(text: str) -> str:
    return re.sub(r"\n{3,}", "\n\n", text).strip() + "\n"


# --------------------------------------------------------------------------- entry point


def render_summary(
    author_meta: dict,
    units: list[Unit],
    resources: list[dict],
    taxonomy: dict[str, dict],
    kb_cfg: dict,
    version: int,
    changelog: list[dict],
    generated_at: str,
) -> dict[str, str]:
    """Return {"summary.md": text}, or a hub plus one "summary - <Domain>.md" per domain when the
    whole summary exceeds kb_cfg["max_doc_chars"]."""
    cfg = {**_DEFAULTS, **{k: v for k, v in (kb_cfg or {}).items() if v is not None}}
    max_chars = int(cfg["max_doc_chars"])
    years = int(cfg["obsolescence_years"])
    res_by_id = {r.get("resource_id", ""): r for r in resources}
    name = author_meta.get("canonical_name") or author_meta.get("author_id") or "Author"

    domains = _domains(units, taxonomy)
    base = {
        "banner": banner_text(version, generated_at),
        "title": f"Summary: {name}",
        "profile": _profile(author_meta, resources, units),
        "sources": _sources_rows(resources),
        "obsolescence_years": years,
        "evolution": _evolution(units, res_by_id),
        "contradictions": _contradictions(units, res_by_id),
        "obsolescence": _obsolescence(units, res_by_id, generated_at, years),
        "glossary": _glossary(units),
        "changelog": [
            {"version": c.get("version", ""), "date": c.get("date", ""), "note": str(c.get("note", "")).replace("|", "/")}
            for c in (changelog or [])
        ],
        "parts": [],
    }
    template = _env().get_template("summary.md.j2")

    full = _tidy(template.render(**base, mode="full", include_cards=True, domains=domains))
    if len(full) <= max_chars or not domains:
        return {"summary.md": full}

    parts = [{"title": f"summary - {d['name']}", "n_cards": d["n_cards"], "url": ""} for d in domains]
    out = {"summary.md": _tidy(template.render(**{**base, "parts": parts}, mode="hub", include_cards=False, domains=[]))}
    for d in domains:
        text = template.render(
            **{**base, "title": f"Summary: {name} - {d['name']}"}, mode="part", include_cards=True, domains=[d]
        )
        out[f"summary - {d['name']}.md"] = _tidy(text)
    return out
